### ISSUE TITLE
Errors are not shown if it happens on initial load

### ISSUE THREAD

**Issue by francoislg** [coveo/react-vapor#621]
I am wondering why no errors are shown when no initial data is provided.

With this line:

```
this.isInitialLoad = props.initialTableData == DEFAULT_TABLE_DATA;
```

(https://github.com/coveo/react-vapor/blob/master/src/components/tables/Table.tsx#L123)

coupled with this condition:

```
const tableBodyNode: React.ReactNode = tableData.displayedIds.length || this.props.tableCompositeState.isLoading || this.isInitialLoad
            ? this.getTableBody()
            : <TableChildBlankSlate {...this.props} />;
```

(https://github.com/coveo/react-vapor/blob/master/src/components/tables/Table.tsx#L173)

The state of table can be `isLoading: false` and `isInError: true`, but the `this.isInitialLoad` condition prevents the error from being shown, thus the UI is shown in "loading" mode, even though there is an error.

I wonder if this "initialLoad" is required. Can we put the `isLoading` state to true by default instead?

Or we could explicitely handle the "isInError" state in the condition:

`!this.props.tableCompositeState.isInError && (tableData.displayedIds.length || this.props.tableCompositeState.isLoading || this.isInitialLoad)`

Thoughts?

**Comment by MichelML** [comment]
- the loading behavior on first load is different than the following loads, we kept this behavior for legacy purposes as the tables in the Admin UI were loading this way prior to react-vapor.  So isInitialLoad is kind of required.
  
- There is surely a problem to solve here, and I'll consider your solution for the fix.

**Comment by MichelML** [comment]
addressed in https://github.com/coveo/react-vapor/pull/686
