### ISSUE TITLE
Button text not aligned correctly when using the `link` property and the `mod-small` modifier.

### ISSUE THREAD

**Issue by lbergeron** [coveo/react-vapor#873]
With react-vapor 2.28.0, when declaring a button this way, the text is on top instead of vertically centered.

I didn't try with react-vapor 3.x though.

```
<Button small enabled primary name="myButton" classes={["mt2"]} link="http://www.google.com" target="_blank" />
```

**Comment by gdostie** [comment]
Fixed by https://github.com/coveo/react-vapor/pull/1191, available in release [v4.3.1](https://github.com/coveo/react-vapor/releases/tag/v4.3.1).
